//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> BirthOfDate { get; set; }
        public string BirthOfPlace { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> FamilyStatusID { get; set; }
        public Nullable<int> MilitaryStatusID { get; set; }
        public Nullable<byte> Height { get; set; }
        public Nullable<int> EyeColorID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string LivingPlace { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public string IssuingAuthority { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual EyeColor EyeColor { get; set; }
        public virtual FamilyStatu FamilyStatu { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MilitaryStatuss MilitaryStatuss { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
